Default: &defaults
  database: litter.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: litter_test.sqlite3
  <<: *defaults

Staging:
  database: litter_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: litter_production.sqlite3
  poolsize: 100
  <<: *defaults
